sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
notifications:
  email: false
before_install:
  - npm i -g npm@^5.0.0
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release